# Generated by Django 5.2.14 on 2026-05-27 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_client_id', models.CharField(blank=True, max_length=80)),
                ('file', models.FileField(upload_to='conversation_attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=160)),
                ('mime_type', models.CharField(max_length=80)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.conversationrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation attachment',
                'verbose_name_plural': 'conversation attachments',
                'indexes': [models.Index(fields=['user', 'conversation', '-created_at'], name='users_conve_user_id_3a1884_idx'), models.Index(fields=['user', 'message_client_id'], name='users_conve_user_id_e28981_idx')],
            },
        ),
    ]
